[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.51"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"